version: '2'

services:
  app:
    image: 'codepower'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  oj:
    image: 'krauchman/sp:oj'
    container_name: oj
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - TASKS_BROKER_URL=redis://redis:6379

  oj-worker:
    image: 'krauchman/sp:oj-worker'
    container_name: oj-worker
    privileged: true
    environment:
      - DB_HOST=db
      - TASKS_BROKER_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  redis:
    image: 'bitnami/redis:7.0.11'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
        - redisdata:/bitnami/redis/data

volumes:
  pgdata:
  redisdata:
