version: '2'

services:
  app:
    image: 'codepower'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  oj:
    image: 'krauchman/sp:oj'
    container_name: oj
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db

  oj-worker:
    image: 'krauchman/sp:oj-worker'
    container_name: oj-worker
    privileged: true
    environment:
      - DB_HOST=db

volumes:
  pgdata:
